### ISSUE TITLE
problem with PHP 7.1.9-1+ubuntu16.04.1+deb.sury.org+1 (cli) 

### ISSUE THREAD

**Issue by fortunatobianconi** [mote0230/dbase-pecl-php7#4]
I tried the procedure with php7.1  and Apache/2.4.18 (Ubuntu).
The extension was not added.
Can you help, please?

**Comment by mote0230** [comment]
Sorry you have to use the extension from pecl now, this one is deprecrated. Something along the lines of "sudo pecl install dbase"

https://pecl.php.net/package/dbase
